In [2]:
import pandas as pd 
import numpy as np


import warnings
warnings.simplefilter('ignore')

In [3]:
df = pd.read_excel(r"E:\Data Science by SRK\PROJECTS\other_data\Regression_project\property_price_prediction_data.xlsx")

In [4]:
df

,size_sq_ft,propertyType,bedrooms,price,AP_dist_km,Aiims_dist_km,NDRLW_dist_km,suburb_Delhi Central,suburb_Delhi East,suburb_Delhi North,suburb_Delhi South,suburb_Delhi West,suburb_Dwarka,suburb_North Delhi,suburb_North West Delhi,suburb_Other,suburb_Rohini,suburb_South West Delhi,suburb_West Delhi
0,5.993961,1,1,9.105091,3.124178,2.494794,2.481289,False,True,False,False,False,False,False,False,False,False,False,False
1,6.957497,0,2,9.903538,3.109144,2.343637,3.228757,False,True,False,False,False,False,False,False,False,False,False,False
2,7.719130,1,2,10.239996,3.162109,2.551746,2.736483,False,True,False,False,False,False,False,False,False,False,False,False
3,7.208600,1,2,10.239996,3.164682,2.563618,2.720278,False,True,False,False,False,False,False,False,False,False,False,False
4,6.111467,0,2,9.433564,3.160942,2.448552,3.450400,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17700,5.602119,1,1,9.615872,2.693788,2.237752,1.439911,False,False,False,False,True,False,False,False,False,False,False,False
17701,6.908755,1,3,10.545368,2.693810,2.237903,1.440214,False,False,False,False,True,False,False,False,False,False,False,False
17702,7.244942,1,1,10.757924,2.625941,2.220053,1.827009,False,False,False,False,True,False,False,False,False,False,False,False
17703,6.803505,1,1,8.987322,2.660821,2.269011,1.753226,False,False,False,False,True,False,False,False,False,False,False,False
17704,6.908755,1,3,10.545368,2.711261,2.265247,1.400796,False,False,False,False,True,False,False,False,False,False,False,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17705 entries, 0 to 17704
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   size_sq_ft               17705 non-null  float64
 1   propertyType             17705 non-null  int64
 2   bedrooms                 17705 non-null  int64
 3   price                    17705 non-null  float64
 4   AP_dist_km               17705 non-null  float64
 5   Aiims_dist_km            17705 non-null  float64
 6   NDRLW_dist_km            17705 non-null  float64
 7   suburb_Delhi Central     17705 non-null  bool
 8   suburb_Delhi East        17705 non-null  bool
 9   suburb_Delhi North       17705 non-null  bool
 10  suburb_Delhi South       17705 non-null  bool
 11  suburb_Delhi West        17705 non-null  bool
 12  suburb_Dwarka            17705 non-null  bool
 13  suburb_North Delhi       17705 non-null  bool
 14  suburb_North West Delhi  17705 non-null  bool
 15  suburb_Other             17705 non-null  bool
 16  suburb_Rohini            17705 non-null  bool
 17  suburb_South West Delhi  17705 non-null  bool
 18  suburb_West Delhi        17705 non-null  bool
dtypes: bool(12), float64(5), int64(2)
memory usage: 1.1 MB

# X and y

In [6]:
X = df.drop(columns = ['price'])
y = df['price']

# Train_Test_Split

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

# Modelling And Evaluation

**Applying hyperparameter tuning for lasso regression**

In [8]:
from sklearn.model_selection import GridSearchCV

# model
from sklearn.linear_model import Lasso
estimator = Lasso()

# parameter and value
param_grid = {"alpha" : list(range(1, 10))}

# Identifying best parameter value(alpha0) within the given vaalues for the given data
model_hp = GridSearchCV(estimator, param_grid, cv=5,scoring = 'r2')

model_hp.fit(X_train, y_train)
model_hp.best_params_

{'alpha': 1}

**BUILD LASSO MODEL USING BEST HYPERPARAMETERS**

In [10]:
from sklearn.linear_model import Lasso
lasso_best = Lasso(alpha = 1)
lasso_best.fit(X_train, y_train)

print("Intercept : ", lasso_best.intercept_)
print("Coefficient : ", lasso_best.coef_)
print("==========================================")

# Prediction And Evaluation on train Data
ypred_train = lasso_best.predict(X_train)

from sklearn.metrics import r2_score
print("Train_R2 : ", r2_score(y_train, ypred_train))

from sklearn.model_selection import cross_val_score
print("Cross_val_score : ", cross_val_score(lasso_best, X_train, y_train, cv = 5).mean())

# PREDICTION AND EVALUATION ON TEST DATA
ypred_test = lasso_best.predict(X_test)
print('Test_r2 : ', r2_score(y_test, ypred_test))

Intercept :  10.02949147705878
Coefficient :  [ 0.  0.  0. -0. -0. -0. -0. -0.  0.  0.  0.  0.  0. -0. -0. -0. -0. -0.]
==========================================
Train_R2 :  0.0
Cross_val_score :  -0.0005729527296577608
Test_r2 :  -0.0001437701496798116