In [1]:
import pandas as pd
import numpy as np



import warnings
warnings.simplefilter('ignore')

In [2]:
df = pd.read_excel(r"E:\Data Science by SRK\PROJECTS\other_data\Regression_project\property_price_prediction_data.xlsx")

In [3]:
df

,size_sq_ft,propertyType,bedrooms,price,AP_dist_km,Aiims_dist_km,NDRLW_dist_km,suburb_Delhi Central,suburb_Delhi East,suburb_Delhi North,suburb_Delhi South,suburb_Delhi West,suburb_Dwarka,suburb_North Delhi,suburb_North West Delhi,suburb_Other,suburb_Rohini,suburb_South West Delhi,suburb_West Delhi
0,5.993961,1,1,9.105091,3.124178,2.494794,2.481289,False,True,False,False,False,False,False,False,False,False,False,False
1,6.957497,0,2,9.903538,3.109144,2.343637,3.228757,False,True,False,False,False,False,False,False,False,False,False,False
2,7.719130,1,2,10.239996,3.162109,2.551746,2.736483,False,True,False,False,False,False,False,False,False,False,False,False
3,7.208600,1,2,10.239996,3.164682,2.563618,2.720278,False,True,False,False,False,False,False,False,False,False,False,False
4,6.111467,0,2,9.433564,3.160942,2.448552,3.450400,False,True,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17700,5.602119,1,1,9.615872,2.693788,2.237752,1.439911,False,False,False,False,True,False,False,False,False,False,False,False
17701,6.908755,1,3,10.545368,2.693810,2.237903,1.440214,False,False,False,False,True,False,False,False,False,False,False,False
17702,7.244942,1,1,10.757924,2.625941,2.220053,1.827009,False,False,False,False,True,False,False,False,False,False,False,False
17703,6.803505,1,1,8.987322,2.660821,2.269011,1.753226,False,False,False,False,True,False,False,False,False,False,False,False
17704,6.908755,1,3,10.545368,2.711261,2.265247,1.400796,False,False,False,False,True,False,False,False,False,False,False,False

# X and y

In [4]:
X = df.drop(columns = ['price'])
y = df['price']

# Train_Test_Split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

# Modelling : Polynomial Regression

**Incresing higher degree of input variable & Applying linear regression**

In [6]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_converter =  PolynomialFeatures(degree = 2, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))

X_train_poly

,0,1,2,3,4,5,6,7,8,9,...,179,180,181,182,183,184,185,186,187,188
0,6.293419,1.0,2.0,2.928661,2.033944,3.923736,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,6.803505,1.0,2.0,2.117647,2.638551,3.966705,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,6.484635,1.0,1.0,2.658738,2.427170,2.297939,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6.908755,2.0,2.0,2.767566,1.418425,3.328348,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6.775366,2.0,2.0,2.641853,2.394662,2.253292,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14159,6.957497,0.0,2.0,3.145992,2.459462,3.001791,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14160,6.685861,0.0,1.0,3.102871,2.337394,3.124514,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14161,7.438972,0.0,3.0,2.097970,2.129595,4.256762,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14162,6.478510,1.0,1.0,2.883759,1.780759,3.389067,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14163,6.111467,0.0,1.0,2.553768,2.104239,4.386633,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# ALL STEPS IN ONE CELL   (DEGREE = 2)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 2, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.822276752760756
Cross_validation_score :  -21438194.579629928
Test R2 :  0.2923407337685212

In [8]:
# ALL STEPS IN ONE CELL   (DEGREE = 3)


# Increasing degree of input variable : 
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter =  PolynomialFeatures(degree = 3, include_bias = False)
X_train_poly = pd.DataFrame(polynomial_converter.fit_transform(X_train))


# Create model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_poly, y_train)

#("Intercept : ",model.intercept_)
#print("coefficients : ", model.coef_)

# Prediction on Train data
ypred_train = model.predict(X_train_poly)


# EVALUATION on Train data
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

#print("Train RMSE : ", np.sqrt(mean_squared_error(y_train, ypred_train)))
print("Train R2 : ", r2_score(y_train, ypred_train))
print("Cross_validation_score : ", cross_val_score(model, X_train_poly, y_train, cv= 5).mean())


# Variable Significance
# ASSUME HERE ALL VARIABLES ARE SIGNIFICANT


# Data preprocessing n test data
X_test_poly = pd.DataFrame(polynomial_converter.transform(X_test))


# prediction on test data
ypred_test = model.predict(X_test_poly)


# Evaluation on Test data
print("Test R2 : ", r2_score(y_test, ypred_test))

Train R2 :  0.8503909233292815
Cross_validation_score :  -5311706890789506.0
Test R2 :  -8538195872896857.0

**This algorithm is not working for this data**